export const TAILWIND_COLORS = {
	'blue-500': {
		textColor: 'text-blue-500',
		bgColor: 'bg-blue-500',
		bgColorHalfOpacity: 'bg-blue-500/50',
		borderColor: 'border-blue-500',
		hexColor: '#3b82f6',
		hover: {
			textColor: 'hover:text-blue-500',
			bgColor: 'hover:bg-blue-500',
			borderColor: 'hover:border-blue-500',
		},
	},
	'emerald-500': {
		textColor: 'text-emerald-500',
		bgColor: 'bg-emerald-500',
		bgColorHalfOpacity: 'bg-emerald-500/50',
		borderColor: 'border-emerald-500',
		hexColor: '#10b981',
		hover: {
			textColor: 'hover:text-emerald-500',
			bgColor: 'hover:bg-emerald-500',
			borderColor: 'hover:border-emerald-500',
		},
	},
	'red-500': {
		textColor: 'text-red-500',
		bgColor: 'bg-red-500',
		bgColorHalfOpacity: 'bg-red-500/50',
		borderColor: 'border-red-500',
		hexColor: '#ef4444',
		hover: {
			textColor: 'hover:text-red-500',
			bgColor: 'hover:bg-red-500',
			borderColor: 'hover:border-red-500',
		},
	},
	'slate-500': {
		textColor: 'text-slate-500',
		bgColor: 'bg-slate-500',
		bgColorHalfOpacity: 'bg-slate-500/50',
		borderColor: 'border-slate-500',
		hexColor: '#64748b',
		hover: {
			textColor: 'hover:text-slate-500',
			bgColor: 'hover:bg-slate-500',
			borderColor: 'hover:border-slate-500',
		},
	},
	'gray-500': {
		textColor: 'text-gray-500',
		bgColor: 'bg-gray-500',
		bgColorHalfOpacity: 'bg-gray-500/50',
		borderColor: 'border-gray-500',
		hexColor: '#6b7280',
		hover: {
			textColor: 'hover:text-gray-500',
			bgColor: 'hover:bg-gray-500',
			borderColor: 'hover:border-gray-500',
		},
	},
	'zinc-500': {
		textColor: 'text-zinc-500',
		bgColor: 'bg-zinc-500',
		bgColorHalfOpacity: 'bg-zinc-500/50',
		borderColor: 'border-zinc-500',
		hexColor: '#71717a',
		hover: {
			textColor: 'hover:text-zinc-500',
			bgColor: 'hover:bg-zinc-500',
			borderColor: 'hover:border-zinc-500',
		},
	},
	'neutral-500': {
		textColor: 'text-neutral-500',
		bgColor: 'bg-neutral-500',
		bgColorHalfOpacity: 'bg-neutral-500/50',
		borderColor: 'border-neutral-500',
		hexColor: '#737373',
		hover: {
			textColor: 'hover:text-neutral-500',
			bgColor: 'hover:bg-neutral-500',
			borderColor: 'hover:border-neutral-500',
		},
	},
	'stone-500': {
		textColor: 'text-stone-500',
		bgColor: 'bg-stone-500',
		bgColorHalfOpacity: 'bg-stone-500/50',
		borderColor: 'border-stone-500',
		hexColor: '#78716c',
		hover: {
			textColor: 'hover:text-stone-500',
			bgColor: 'hover:bg-stone-500',
			borderColor: 'hover:border-stone-500',
		},
	},
	'orange-500': {
		textColor: 'text-orange-500',
		bgColor: 'bg-orange-500',
		bgColorHalfOpacity: 'bg-orange-500/50',
		borderColor: 'border-orange-500',
		hexColor: '#f97316',
		hover: {
			textColor: 'hover:text-orange-500',
			bgColor: 'hover:bg-orange-500',
			borderColor: 'hover:border-orange-500',
		},
	},
	'amber-500': {
		textColor: 'text-amber-500',
		bgColor: 'bg-amber-500',
		bgColorHalfOpacity: 'bg-amber-500/50',
		borderColor: 'border-amber-500',
		hexColor: '#f59e0b',
		hover: {
			textColor: 'hover:text-amber-500',
			bgColor: 'hover:bg-amber-500',
			borderColor: 'hover:border-amber-500',
		},
	},
	'yellow-500': {
		textColor: 'text-yellow-500',
		bgColor: 'bg-yellow-500',
		bgColorHalfOpacity: 'bg-yellow-500/50',
		borderColor: 'border-yellow-500',
		hexColor: '#eab308',
		hover: {
			textColor: 'hover:text-yellow-500',
			bgColor: 'hover:bg-yellow-500',
			borderColor: 'hover:border-yellow-500',
		},
	},
	'lime-500': {
		textColor: 'text-lime-500',
		bgColor: 'bg-lime-500',
		bgColorHalfOpacity: 'bg-lime-500/50',
		borderColor: 'border-lime-500',
		hexColor: '#84cc16',
		hover: {
			textColor: 'hover:text-lime-500',
			bgColor: 'hover:bg-lime-500',
			borderColor: 'hover:border-lime-500',
		},
	},
	'green-500': {
		textColor: 'text-green-500',
		bgColor: 'bg-green-500',
		bgColorHalfOpacity: 'bg-green-500/50',
		borderColor: 'border-green-500',
		hexColor: '#22c55e',
		hover: {
			textColor: 'hover:text-green-500',
			bgColor: 'hover:bg-green-500',
			borderColor: 'hover:border-green-500',
		},
	},
	'teal-500': {
		textColor: 'text-teal-500',
		bgColor: 'bg-teal-500',
		bgColorHalfOpacity: 'bg-teal-500/50',
		borderColor: 'border-teal-500',
		hexColor: '#14b8a6',
		hover: {
			textColor: 'hover:text-teal-500',
			bgColor: 'hover:bg-teal-500',
			borderColor: 'hover:border-teal-500',
		},
	},
	'cyan-500': {
		textColor: 'text-cyan-500',
		bgColor: 'bg-cyan-500',
		bgColorHalfOpacity: 'bg-cyan-500/50',
		borderColor: 'border-cyan-500',
		hexColor: '#06b6d4',
		hover: {
			textColor: 'hover:text-cyan-500',
			bgColor: 'hover:bg-cyan-500',
			borderColor: 'hover:border-cyan-500',
		},
	},
	'sky-500': {
		textColor: 'text-sky-500',
		bgColor: 'bg-sky-500',
		bgColorHalfOpacity: 'bg-sky-500/50',
		borderColor: 'border-sky-500',
		hexColor: '#0ea5e9',
		hover: {
			textColor: 'hover:text-sky-500',
			bgColor: 'hover:bg-sky-500',
			borderColor: 'hover:border-sky-500',
		},
	},
	'indigo-500': {
		textColor: 'text-indigo-500',
		bgColor: 'bg-indigo-500',
		bgColorHalfOpacity: 'bg-indigo-500/50',
		borderColor: 'border-indigo-500',
		hexColor: '#6366f1',
		hover: {
			textColor: 'hover:text-indigo-500',
			bgColor: 'hover:bg-indigo-500',
			borderColor: 'hover:border-indigo-500',
		},
	},
	'violet-500': {
		textColor: 'text-violet-500',
		bgColor: 'bg-violet-500',
		bgColorHalfOpacity: 'bg-violet-500/50',
		borderColor: 'border-violet-500',
		hexColor: '#8b5cf6',
		hover: {
			textColor: 'hover:text-violet-500',
			bgColor: 'hover:bg-violet-500',
			borderColor: 'hover:border-violet-500',
		},
	},
	'purple-500': {
		textColor: 'text-purple-500',
		bgColor: 'bg-purple-500',
		bgColorHalfOpacity: 'bg-purple-500/50',
		borderColor: 'border-purple-500',
		hexColor: '#a855f7',
		hover: {
			textColor: 'hover:text-purple-500',
			bgColor: 'hover:bg-purple-500',
			borderColor: 'hover:border-purple-500',
		},
	},
	'fuchsia-500': {
		textColor: 'text-fuchsia-500',
		bgColor: 'bg-fuchsia-500',
		bgColorHalfOpacity: 'bg-fuchsia-500/50',
		borderColor: 'border-fuchsia-500',
		hexColor: '#d946ef',
		hover: {
			textColor: 'hover:text-fuchsia-500',
			bgColor: 'hover:bg-fuchsia-500',
			borderColor: 'hover:border-fuchsia-500',
		},
	},
	'pink-500': {
		textColor: 'text-pink-500',
		bgColor: 'bg-pink-500',
		bgColorHalfOpacity: 'bg-pink-500/50',
		borderColor: 'border-pink-500',
		hexColor: '#ec4899',
		hover: {
			textColor: 'hover:text-pink-500',
			bgColor: 'hover:bg-pink-500',
			borderColor: 'hover:border-pink-500',
		},
	},
	'rose-500': {
		textColor: 'text-rose-500',
		bgColor: 'bg-rose-500',
		bgColorHalfOpacity: 'bg-rose-500/50',
		borderColor: 'border-rose-500',
		hexColor: '#f43f5e',
		hover: {
			textColor: 'hover:text-rose-500',
			bgColor: 'hover:bg-rose-500',
			borderColor: 'hover:border-rose-500',
		},
	},
};
