export const DEFAULT_DAILY_COMPLETED_TASKS_MEDALS = [
	{
		name: 'Complete 30 Tasks',
		requiredCompletedTasks: 30,
		interval: 'daily',
		intervalsEarned: [],
	},
	{
		name: 'Complete 25 Tasks',
		requiredCompletedTasks: 25,
		interval: 'daily',
		intervalsEarned: [],
	},
	{
		name: 'Complete 20 Tasks',
		requiredCompletedTasks: 20,
		interval: 'daily',
		intervalsEarned: [],
	},
	{
		name: 'Complete 15 Tasks',
		requiredCompletedTasks: 15,
		interval: 'daily',
		intervalsEarned: [],
	},
	{
		name: 'Complete 10 Tasks',
		requiredCompletedTasks: 10,
		interval: 'daily',
		intervalsEarned: [],
	},
	{
		name: 'Complete 5 Tasks',
		requiredCompletedTasks: 5,
		interval: 'daily',
		intervalsEarned: [],
	},
	{
		name: 'Complete 1 Task',
		requiredCompletedTasks: 1,
		interval: 'daily',
		intervalsEarned: [],
	},
];

export const DEFAULT_WEEKLY_COMPLETED_TASKS_MEDALS = [
	{
		name: 'Complete 200 Tasks',
		requiredCompletedTasks: 200,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 190 Tasks',
		requiredCompletedTasks: 190,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 180 Tasks',
		requiredCompletedTasks: 180,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 170 Tasks',
		requiredCompletedTasks: 170,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 160 Tasks',
		requiredCompletedTasks: 160,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 150 Tasks',
		requiredCompletedTasks: 150,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 140 Tasks',
		requiredCompletedTasks: 140,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 130 Tasks',
		requiredCompletedTasks: 130,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 120 Tasks',
		requiredCompletedTasks: 120,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 110 Tasks',
		requiredCompletedTasks: 110,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 100 Tasks',
		requiredCompletedTasks: 100,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 90 Tasks',
		requiredCompletedTasks: 90,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 80 Tasks',
		requiredCompletedTasks: 80,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 70 Tasks',
		requiredCompletedTasks: 70,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 60 Tasks',
		requiredCompletedTasks: 60,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 50 Tasks',
		requiredCompletedTasks: 50,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 40 Tasks',
		requiredCompletedTasks: 40,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 30 Tasks',
		requiredCompletedTasks: 30,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 20 Tasks',
		requiredCompletedTasks: 20,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 10 Tasks',
		requiredCompletedTasks: 10,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 5 Tasks',
		requiredCompletedTasks: 5,
		interval: 'weekly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 1 Task',
		requiredCompletedTasks: 1,
		interval: 'weekly',
		intervalsEarned: [],
	}

];

export const DEFAULT_MONTHLY_COMPLETED_TASKS_MEDALS = [
	{
		name: 'Complete 1000 Tasks',
		requiredCompletedTasks: 1000,
		interval: 'monthly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 900 Tasks',
		requiredCompletedTasks: 900,
		interval: 'monthly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 800 Tasks',
		requiredCompletedTasks: 800,
		interval: 'monthly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 700 Tasks',
		requiredCompletedTasks: 700,
		interval: 'monthly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 600 Tasks',
		requiredCompletedTasks: 600,
		interval: 'monthly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 500 Tasks',
		requiredCompletedTasks: 500,
		interval: 'monthly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 400 Tasks',
		requiredCompletedTasks: 400,
		interval: 'monthly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 300 Tasks',
		requiredCompletedTasks: 300,
		interval: 'monthly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 250 Tasks',
		requiredCompletedTasks: 250,
		interval: 'monthly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 200 Tasks',
		requiredCompletedTasks: 200,
		interval: 'monthly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 150 Tasks',
		requiredCompletedTasks: 150,
		interval: 'monthly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 100 Tasks',
		requiredCompletedTasks: 100,
		interval: 'monthly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 90 Tasks',
		requiredCompletedTasks: 90,
		interval: 'monthly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 80 Tasks',
		requiredCompletedTasks: 80,
		interval: 'monthly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 70 Tasks',
		requiredCompletedTasks: 70,
		interval: 'monthly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 60 Tasks',
		requiredCompletedTasks: 60,
		interval: 'monthly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 50 Tasks',
		requiredCompletedTasks: 50,
		interval: 'monthly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 25 Tasks',
		requiredCompletedTasks: 25,
		interval: 'monthly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 10 Tasks',
		requiredCompletedTasks: 10,
		interval: 'monthly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 5 Tasks',
		requiredCompletedTasks: 5,
		interval: 'monthly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 1 Task',
		requiredCompletedTasks: 1,
		interval: 'monthly',
		intervalsEarned: [],
	},
];

export const DEFAULT_YEARLY_COMPLETED_TASKS_MEDALS = [
	{
		name: 'Complete 5000 Tasks',
		requiredCompletedTasks: 5000,
		interval: 'yearly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 4500 Tasks',
		requiredCompletedTasks: 4500,
		interval: 'yearly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 4000 Tasks',
		requiredCompletedTasks: 4000,
		interval: 'yearly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 3500 Tasks',
		requiredCompletedTasks: 3500,
		interval: 'yearly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 3000 Tasks',
		requiredCompletedTasks: 3000,
		interval: 'yearly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 2500 Tasks',
		requiredCompletedTasks: 2500,
		interval: 'yearly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 2000 Tasks',
		requiredCompletedTasks: 2000,
		interval: 'yearly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 1500 Tasks',
		requiredCompletedTasks: 1500,
		interval: 'yearly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 1000 Tasks',
		requiredCompletedTasks: 1000,
		interval: 'yearly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 900 Tasks',
		requiredCompletedTasks: 900,
		interval: 'yearly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 800 Tasks',
		requiredCompletedTasks: 800,
		interval: 'yearly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 700 Tasks',
		requiredCompletedTasks: 700,
		interval: 'yearly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 600 Tasks',
		requiredCompletedTasks: 600,
		interval: 'yearly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 500 Tasks',
		requiredCompletedTasks: 500,
		interval: 'yearly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 100 Tasks',
		requiredCompletedTasks: 100,
		interval: 'yearly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 50 Tasks',
		requiredCompletedTasks: 50,
		interval: 'yearly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 25 Tasks',
		requiredCompletedTasks: 25,
		interval: 'yearly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 10 Tasks',
		requiredCompletedTasks: 10,
		interval: 'yearly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 5 Tasks',
		requiredCompletedTasks: 5,
		interval: 'yearly',
		intervalsEarned: [],
	},
	{
		name: 'Complete 1 Task',
		requiredCompletedTasks: 1,
		interval: 'yearly',
		intervalsEarned: [],
	},
];
